=== carlosDAM2905/proyectosxml/XSD/ejercicios-xsd/pagos/pagos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pagos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" default="A" maxOccurs="3"/>
                <xs:element name="fechaNacimiento" type="xs:date"/>
                <xs:element name="hora" maxOccurs="unbounded"/>
                <xs:element name="precio" type="xs:decimal"/>
                <xs:element name="cantidad" fixed="678"/>
                <xs:element name="pagado" type="xs:boolean" default="false"/>
            </xs:sequence>
            <xs:attribute name="dni"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== carlosDAM2905/proyectosxml/XSD/ejercicios-xsd/pagos/pagos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pagos
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="pagos.xsd">
    <nombre>Javier Toledano</nombre>
    <fechaNacimiento>1979-02-04</fechaNacimiento>
    <hora>23:55:15</hora>
    <hora>23:55:15</hora>
    <precio>123.56</precio>
    <cantidad>678</cantidad>
    <pagado>true</pagado>
</pagos>


<!--El elemento nombre puede aparecer como m치ximo 3 veces y su valor por defecto es "A".-->

<!--El elemento hora puede aparecer un numero infinito de veces.-->

<!--El valor por defecto de pagado es false.-->

<!--La cantidad es fija y es siempre 678.-->


<!--A침ade los atributos siguientes: -->

<!--Atributo dni requerido obligatoriamente y con una longitud m치xima de 10 caracteres en el elemento nombre.-->

<!--Atributo edad entre 16 y 24 a침os, en el elemento FechaNacimiento.-->
